import { defineConfig } from "@iringo/arguments-builder";

export default defineConfig({
	output: {
		surge: {
			path: "./dist/iRingo.WeatherKit.sgmodule",
			transformEgern: {
				enable: true,
				path: "./dist/iRingo.WeatherKit.yaml",
			},
		},
		loon: {
			path: "./dist/iRingo.WeatherKit.plugin",
		},
		customItems: [
			{
				path: "./dist/iRingo.WeatherKit.snippet",
				template: "./template/quantumultx.handlebars",
			},
			{
				path: "./dist/iRingo.WeatherKit.stoverride",
				template: "./template/stash.handlebars",
			},
		],
		dts: {
			isExported: true,
			path: "./src/types.d.ts",
		},
		boxjsSettings: {
			path: "./template/boxjs.settings.json",
			scope: "@iRingo.WeatherKit.Settings",
		},
	},
	args: [
		{
			key: "DataSets.Targets",
			name: "[数据集] 修改地区",
			defaultValue: "CN|HK|MO|TW",
			type: "string",
			description: "正则表达式，只修改指定地区的数据集。",
		},
		{
			key: "DataSets.Value",
			name: "[数据集]",
			defaultValue: ["airQuality", "currentWeather", "forecastDaily", "forecastHourly", "forecastNextHour", "locationInfo", "news", "historicalComparisons", "weatherAlerts", "weatherChanges"],
			type: "array",
			description: "选中的数据集会被包含在请求中。",
			options: [
				{ key: "airQuality", label: "空气质量" },
				{ key: "currentWeather", label: "当前天气" },
				{ key: "forecastDaily", label: "每日预报" },
				{ key: "forecastHourly", label: "每小时预报" },
				{ key: "forecastNextHour", label: "未来一小时降水强度" },
				{ key: "locationInfo", label: "位置信息" },
				{ key: "news", label: "新闻" },
				{ key: "historicalComparisons", label: "历史对比" },
				{ key: "weatherAlerts", label: "天气预警" },
				{ key: "weatherChanges", label: "天气变化" },
			],
		},
		{
			key: "Weather.Targets",
			name: "[天气] 替换地区",
			defaultValue: "CN",
			type: "string",
			description: "正则表达式，只替换指定地区的天气。",
		},
		{
			key: "Weather.Provider",
			name: "[天气] 数据源",
			defaultValue: "WeatherKit",
			type: "string",
			options: [
				{ key: "WeatherKit", label: "WeatherKit (不进行替换)" },
				{ key: "ColorfulClouds", label: "彩云天气" },
				{ key: "QWeather", label: "和风天气" },
			],
			description: "使用选定的数据源替换天气数据。",
		},
		{
			key: "NextHour.Targets",
			name: "[未来一小时降水强度] 填补地区",
			defaultValue: "*",
			type: "string",
			description: "正则表达式，只填补指定地区的未来一小时降水强度。",
		},
		{
			key: "NextHour.Provider",
			name: "[未来一小时降水强度] 数据源",
			defaultValue: "ColorfulClouds",
			type: "string",
			options: [
				{ key: "WeatherKit", label: "WeatherKit (不进行填补)" },
				{ key: "ColorfulClouds", label: "彩云天气" },
				{ key: "QWeather", label: "和风天气" },
			],
			description: "使用选定的数据源填充未来一小时降水强度的数据。",
		},
		{
			key: "AirQuality.Current.Fill",
			name: "[空气质量 - 今日] 填补地区",
			defaultValue: "CN|HK|MO|TW",
			type: "string",
			description: "正则表达式，只填补指定地区的今日空气质量数据。",
		},
		{
			key: "AirQuality.Current.Pollutants.Provider",
			name: "[空气质量 - 今日 - 污染物] 数据源",
			defaultValue: "ColorfulClouds",
			type: "string",
			options: [
				{ key: "ColorfulClouds", label: "彩云天气" },
				{ key: "QWeather", label: "和风天气" },
			],
			description: "使用选定的数据源填充污染物数据。",
		},
		{
			key: "AirQuality.Current.Index.Replace",
			name: "[空气质量 - 今日 - 空气质量指数] 替换目标",
			defaultValue: ["HJ6332012"],
			type: "array",
			options: [
				{ key: "HJ6332012", label: "中国 (HJ 633—2012)" },
				{ key: "EPA_NowCast", label: "美国 (EPA NowCast)" },
			],
			description: "替换指定标准的空气质量指数。",
		},
		{
			key: "AirQuality.Current.Index.Provider",
			name: "[空气质量 - 今日 - 空气质量指数] 数据源",
			defaultValue: "iRingo",
			type: "string",
			options: [
				{ key: "iRingo", label: "iRingo内置算法" },
				{ key: "ColorfulCloudsUS", label: "彩云天气（美标，EPA 454/B-18-007）" },
				{ key: "ColorfulCloudsCN", label: "彩云天气（国标，HJ 633—2012）" },
				{ key: "QWeather", label: "和风天气（国标，HJ 633—2012）" },
				{ key: "WAQI", label: "The World Air Quality Project (InstantCast)" },
			],
			description: "使用选定的数据源填充空气质量指数数据。彩云天气（美标）为2018年9月版（EPA-454/B-18-007），WAQI是基于2018年9月版美标（EPA-454/B-18-007）的InstantCast。",
		},
		{
			key: "AirQuality.Current.Index.ForceCNPrimaryPollutants",
			name: "[空气质量 - 今日 - 空气质量指数] 强制显示国标主要污染物",
			defaultValue: true,
			type: "boolean",
			description: "忽略国标（HJ 633—2012）的AQI > 50规定，始终将IAQI最大的空气污染物作为主要污染物。",
		},
		{
			key: "AirQuality.Comparison.Fill",
			name: "[空气质量 - 对比昨日] 填补地区",
			defaultValue: "CN|HK|MO|TW",
			type: "string",
			description: "正则表达式，只填补指定地区的对比昨日数据。",
		},
		{
			key: "AirQuality.Comparison.ReplaceWhenCurrentChange",
			name: "[空气质量 - 对比昨日] 数据变化时替换",
			defaultValue: false,
			type: "boolean",
			description: "即使已有对比昨日数据，当今日空气质量指数发生变化时，替换对比昨日数据。",
		},
		{
			key: "AirQuality.Comparison.Yesterday.PollutantsProvider",
			name: "[空气质量 - 对比昨日 - 昨日 - 污染物] 数据源",
			defaultValue: "QWeather",
			type: "string",
			options: [
				{ key: "QWeather", label: "和风天气" },
			],
			description: "为iRingo内置算法提供污染物数据，计算出昨日的空气质量指数。",
		},
		{
			key: "AirQuality.Comparison.Yesterday.IndexProvider",
			name: "[空气质量 - 对比昨日 - 昨日 - 空气质量指数] 数据源",
			defaultValue: "ColorfulCloudsUS",
			type: "string",
			options: [
				{ key: "iRingo", label: "iRingo内置算法" },
				{ key: "ColorfulCloudsUS", label: "彩云天气（美标），EPA 454/B-18-007" },
				{ key: "ColorfulCloudsCN", label: "彩云天气（国标，HJ 633—2012）" },
				{ key: "QWeather", label: "和风天气（国标，HJ 633—2012）" },
			],
			description: "用来和今日空气质量指数对比的数据。iRingo内置算法需要昨日污染物数据，彩云天气（美标）为2018年9月版（EPA-454/B-18-007），WAQI是基于2018年9月版美标（EPA-454/B-18-007）的InstantCast。",
		},
		{
			key: "AirQuality.iRingoAlgorithm",
			name: "[空气质量 - iRingo内置算法] 算法",
			defaultValue: "UBA",
			type: "string",
			options: [
				{ key: "UBA", label: "德国LQI（FB001846）" },
				{ key: "EU_EAQI", label: "欧盟EAQI（ETC HE Report 2024/17）" },
				{ key: "WAQI_InstantCast_US", label: "美标WAQI InstantCast（EPA-454/B-24-002）" },
				{ key: "WAQI_InstantCast_CN", label: "国标WAQI InstantCast（HJ 633—2012）" },
			],
			description: "使用内置算法，通过污染物数据本地计算空气指数。",
		},
		{
			key: "API.ColorfulClouds.Token",
			name: "[API] 彩云天气令牌",
			defaultValue: "",
			type: "string",
			placeholder: "123456789123456789abcdefghijklmnopqrstuv",
			description: "彩云天气 API 令牌",
		},
		{
			key: "API.QWeather.Host",
			name: "[API] 和风天气主机",
			defaultValue: "devapi.qweather.com",
			type: "string",
			placeholder: "devapi.qweather.com",
			description: "和风天气 API 使用的主机名",
		},
		{
			key: "API.QWeather.Token",
			name: "[API] 和风天气令牌",
			defaultValue: "",
			type: "string",
			placeholder: "123456789123456789abcdefghijklmnopqrstuv",
			description: "和风天气 API 令牌",
		},
		{
			key: "API.WAQI.Token",
			name: "[API] WAQI 令牌",
			defaultValue: "",
			type: "string",
			placeholder: "123456789123456789abcdefghijklmnopqrstuv",
			description: "WAQI API 令牌，填写此字段将自动使用WAQI高级API",
		},
		{
			key: "LogLevel",
			name: "[调试] 日志等级",
			type: "string",
			defaultValue: "WARN",
			description: "选择脚本日志的输出等级，低于所选等级的日志将全部输出。",
			options: [
				{ key: "OFF", label: "关闭" },
				{ key: "ERROR", label: "❌ 错误" },
				{ key: "WARN", label: "⚠️ 警告" },
				{ key: "INFO", label: "ℹ️ 信息" },
				{ key: "DEBUG", label: "🅱️ 调试" },
				{ key: "ALL", label: "全部" },
			],
		},
	],
});
