name: Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - dev

permissions:
  actions: read
  contents: read

jobs:
  debug:
    uses: ./.github/workflows/dev.yml
    secrets: inherit
  deploy:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: artifact
      - name: Deploy Request
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/request.dev.bundle.js
      - name: Deploy Response
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/response.dev.bundle.js
      - name: Deploy Surge Module
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/iRingo.WeatherKit.dev.sgmodule
      - name: Deploy Loon Plugin
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/iRingo.WeatherKit.dev.plugin
      - name: Deploy Quantumult X Snippet
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/iRingo.WeatherKit.dev.snippet
      - name: Deploy Stash Override
        uses: exuanbo/actions-deploy-gist@main
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 862db28df04be7523476d10b61b128f2
          gist_description: " iRingo: 🌤 WeatherKit β"
          file_path: dist/iRingo.WeatherKit.dev.stoverride
