name: Pre-Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*.*.*-alpha*'
      - 'v*.*.*-beta*'

permissions:
  actions: read
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  pre-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: output
      - name: Publish Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.js
            modules/*
          prerelease: true
